const recipes = [
  {
    id: 0,
    title: "Mediterranean Herb-Crusted Chicken with Quinoa",
    prepTime: "15 minutes",
    cookTime: "25 minutes",
    servings: "4 servings",
    healthNote: "Rich in lean protein and fiber. Olive oil and herbs provide heart-healthy antioxidants that help reduce LDL cholesterol.",
    ingredients: [
      "4 boneless, skinless chicken breasts (6 oz each)",
      "1 cup quinoa",
      "2 cups low-sodium chicken broth",
      "3 tbsp extra virgin olive oil",
      "2 cloves garlic, minced",
      "2 tsp dried oregano",
      "1 tsp dried thyme",
      "1 tsp dried rosemary",
      "2 lemons (juiced and zested)",
      "2 cups fresh broccoli florets",
      "1 cup cherry tomatoes, halved",
      "Salt and black pepper to taste",
      "2 tbsp fresh parsley, chopped"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Pat chicken breasts dry and season with salt and pepper.",
      "Mix 2 tbsp olive oil, minced garlic, oregano, thyme, rosemary, and lemon zest in a small bowl.",
      "Rub herb mixture all over chicken breasts and let marinate for 10 minutes.",
      "Heat remaining olive oil in an oven-safe skillet over medium-high heat. Sear chicken for 3-4 minutes per side until golden.",
      "Transfer skillet to oven and bake for 12-15 minutes until internal temperature reaches 165°F (74°C).",
      "Meanwhile, rinse quinoa and cook in chicken broth according to package directions (about 15 minutes).",
      "Steam broccoli for 4-5 minutes until tender-crisp. Toss with lemon juice and cherry tomatoes.",
      "Let chicken rest for 5 minutes, then slice. Serve over quinoa with vegetables, garnished with fresh parsley."
    ],
    youtubeSearch: "herb crusted chicken quinoa mediterranean"
  },
  {
    id: 1,
    title: "Stuffed Bell Peppers with Turkey and Brown Rice",
    prepTime: "20 minutes",
    cookTime: "35 minutes",
    servings: "4 servings",
    healthNote: "High in fiber from brown rice and vegetables. Lean turkey provides protein while bell peppers offer vitamin C and antioxidants.",
    ingredients: [
      "4 large bell peppers (any color), tops cut and seeds removed",
      "1 lb lean ground turkey (93% lean)",
      "1 cup cooked brown rice",
      "1 can (14.5 oz) diced tomatoes, drained",
      "2 cloves garlic, minced",
      "1 cup low-sodium vegetable broth",
      "1/2 cup part-skim mozzarella cheese, shredded",
      "2 tbsp tomato paste",
      "1 tsp dried basil",
      "1 tsp dried oregano",
      "1/2 tsp smoked paprika",
      "2 tbsp olive oil",
      "Salt and black pepper to taste",
      "2 tbsp fresh basil, chopped"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Lightly brush bell peppers with 1 tbsp olive oil and season inside with salt and pepper.",
      "Heat remaining olive oil in a large skillet over medium heat. Add ground turkey and cook for 6-8 minutes, breaking it up as it cooks.",
      "Add minced garlic, tomato paste, dried basil, oregano, and paprika. Cook for 2 minutes until fragrant.",
      "Stir in diced tomatoes and cooked brown rice. Season with salt and pepper. Cook for 3-4 minutes until heated through.",
      "Remove from heat and let cool slightly. Stir in half of the mozzarella cheese.",
      "Stuff each bell pepper with the turkey and rice mixture, packing gently. Place in a baking dish.",
      "Pour vegetable broth around the peppers in the dish. Cover with foil and bake for 25 minutes.",
      "Remove foil, top with remaining cheese, and bake uncovered for 8-10 minutes until peppers are tender and cheese is melted. Garnish with fresh basil."
    ],
    youtubeSearch: "stuffed bell peppers turkey brown rice healthy"
  },
  {
    id: 2,
    title: "Hearty Lentil and Sweet Potato Stew",
    prepTime: "15 minutes",
    cookTime: "30 minutes",
    servings: "6 servings",
    healthNote: "Packed with soluble fiber from lentils and sweet potatoes, which helps lower LDL cholesterol. Rich in plant-based protein and beta-carotene.",
    ingredients: [
      "1 1/2 cups dried red lentils, rinsed",
      "2 large sweet potatoes, peeled and cubed (about 3 cups)",
      "3 large carrots, sliced",
      "3 celery stalks, chopped",
      "4 cups low-sodium vegetable broth",
      "1 can (14.5 oz) diced tomatoes",
      "3 cloves garlic, minced",
      "2 tbsp olive oil",
      "2 tsp ground cumin",
      "1 tsp turmeric",
      "1 tsp smoked paprika",
      "1/2 tsp ground cinnamon",
      "2 bay leaves",
      "Salt and black pepper to taste",
      "2 cups fresh spinach",
      "1/4 cup fresh cilantro, chopped"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add carrots and celery, cook for 5-6 minutes until slightly softened.",
      "Add minced garlic, cumin, turmeric, paprika, and cinnamon. Cook for 1 minute until fragrant.",
      "Add sweet potato cubes, lentils, diced tomatoes, vegetable broth, and bay leaves. Bring to a boil.",
      "Reduce heat to low, cover, and simmer for 20-25 minutes until lentils are tender and sweet potatoes are easily pierced with a fork.",
      "Season with salt and pepper to taste. Remove bay leaves.",
      "Stir in fresh spinach and cook for 2-3 minutes until wilted.",
      "Ladle into bowls and garnish with fresh cilantro. Serve with whole grain bread if desired."
    ],
    youtubeSearch: "lentil sweet potato stew healthy vegetarian"
  },
  {
    id: 3,
    title: "Whole Wheat Pasta with Roasted Vegetables and Herbs",
    prepTime: "15 minutes",
    cookTime: "25 minutes",
    servings: "4 servings",
    healthNote: "Whole wheat pasta provides fiber and B vitamins. Olive oil and colorful vegetables supply antioxidants that support heart health.",
    ingredients: [
      "12 oz whole wheat penne pasta",
      "2 medium zucchini, sliced into half-moons",
      "1 large eggplant, cubed",
      "2 cups cherry tomatoes",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "4 cloves garlic, minced",
      "1/4 cup extra virgin olive oil",
      "2 tsp dried Italian seasoning",
      "1 tsp dried thyme",
      "1/2 cup fresh basil leaves, torn",
      "1/4 cup pine nuts, toasted",
      "1/4 cup grated Parmesan cheese",
      "Salt and black pepper to taste",
      "Red pepper flakes (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Line a large baking sheet with parchment paper.",
      "Toss zucchini, eggplant, cherry tomatoes, and bell peppers with 3 tbsp olive oil, Italian seasoning, thyme, salt, and pepper.",
      "Spread vegetables in a single layer on the baking sheet. Roast for 20-25 minutes until tender and lightly caramelized.",
      "Meanwhile, cook pasta according to package directions until al dente. Reserve 1/2 cup pasta water before draining.",
      "Heat remaining olive oil in a large skillet over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Add the roasted vegetables to the skillet and toss gently to combine.",
      "Add drained pasta and toss with vegetables. Add pasta water gradually if needed to create a light sauce.",
      "Remove from heat, stir in fresh basil and toasted pine nuts. Serve immediately with Parmesan cheese and red pepper flakes if desired."
    ],
    youtubeSearch: "whole wheat pasta roasted vegetables mediterranean"
  },
  {
    id: 4,
    title: "Spiced Chickpea and Avocado Power Bowls",
    prepTime: "15 minutes",
    cookTime: "15 minutes",
    servings: "4 servings",
    healthNote: "Chickpeas provide soluble fiber and plant protein. Avocados contain monounsaturated fats that help improve cholesterol levels.",
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "2 ripe avocados, sliced",
      "4 cups mixed greens (spinach, arugula, kale)",
      "1 cup quinoa, cooked",
      "1 large cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 red cabbage, thinly sliced",
      "3 tbsp olive oil",
      "2 tsp ground cumin",
      "1 tsp smoked paprika",
      "1/2 tsp turmeric",
      "1/4 tsp cayenne pepper",
      "2 limes, juiced",
      "2 tbsp tahini",
      "1 tbsp maple syrup",
      "Salt and black pepper to taste",
      "1/4 cup pumpkin seeds, toasted",
      "Fresh cilantro for garnish"
    ],
    instructions: [
      "Heat 2 tbsp olive oil in a large skillet over medium heat. Add chickpeas and cook for 2-3 minutes.",
      "Add cumin, paprika, turmeric, and cayenne to chickpeas. Stir and cook for 5-7 minutes until chickpeas are lightly crispy and well-coated with spices.",
      "Season with salt and pepper, then remove from heat and let cool slightly.",
      "In a small bowl, whisk together lime juice, tahini, maple syrup, remaining olive oil, salt, and pepper to make the dressing.",
      "Divide cooked quinoa among 4 bowls as the base.",
      "Top each bowl with mixed greens, spiced chickpeas, avocado slices, cucumber, cherry tomatoes, and red cabbage.",
      "Drizzle with tahini dressing and sprinkle with toasted pumpkin seeds.",
      "Garnish with fresh cilantro and serve immediately with lime wedges on the side."
    ],
    youtubeSearch: "chickpea avocado power bowl healthy meal prep"
  },
  {
    id: 5,
    title: "Steel-Cut Oats with Berries and Almonds",
    prepTime: "5 minutes",
    cookTime: "25 minutes",
    servings: "4 servings",
    healthNote: "Steel-cut oats are rich in beta-glucan, a soluble fiber that actively reduces LDL cholesterol. Berries provide antioxidants and almonds add heart-healthy fats.",
    ingredients: [
      "1 cup steel-cut oats",
      "4 cups water",
      "1 cup unsweetened almond milk",
      "2 tbsp maple syrup",
      "1 tsp vanilla extract",
      "1/2 tsp ground cinnamon",
      "1/4 tsp salt",
      "1 cup fresh blueberries",
      "1 cup fresh strawberries, sliced",
      "1/2 cup sliced almonds, toasted",
      "2 tbsp ground flaxseed",
      "2 tbsp chia seeds",
      "1 banana, sliced",
      "Additional maple syrup for serving"
    ],
    instructions: [
      "Bring water to a boil in a medium saucepan. Add steel-cut oats and reduce heat to low.",
      "Simmer uncovered for 20-25 minutes, stirring occasionally, until oats are tender and creamy.",
      "Stir in almond milk, maple syrup, vanilla, cinnamon, and salt. Cook for 2-3 more minutes.",
      "Remove from heat and let stand for 2 minutes to thicken.",
      "Divide oatmeal among 4 bowls. Top with fresh berries, banana slices, and toasted almonds.",
      "Sprinkle with ground flaxseed and chia seeds for extra fiber and omega-3s.",
      "Drizzle with additional maple syrup if desired and serve warm."
    ],
    youtubeSearch: "steel cut oats berries almonds healthy breakfast"
  },
  {
    id: 6,
    title: "Black Bean and Sweet Potato Tacos with Cilantro Lime Sauce",
    prepTime: "15 minutes",
    cookTime: "20 minutes",
    servings: "4 servings",
    healthNote: "Black beans are excellent sources of soluble fiber that helps lower cholesterol. Sweet potatoes provide beta-carotene and additional fiber for heart health.",
    ingredients: [
      "2 large sweet potatoes, peeled and diced",
      "2 cans (15 oz each) black beans, drained and rinsed",
      "8 corn tortillas",
      "3 tbsp olive oil",
      "2 tsp ground cumin",
      "1 tsp chili powder",
      "1/2 tsp smoked paprika",
      "1/4 tsp cayenne pepper",
      "2 limes, juiced",
      "1/2 cup plain Greek yogurt",
      "1/4 cup fresh cilantro, chopped",
      "2 cups shredded purple cabbage",
      "1 avocado, sliced",
      "1/4 cup pumpkin seeds",
      "Salt and black pepper to taste",
      "Hot sauce (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Toss diced sweet potatoes with 2 tbsp olive oil, cumin, chili powder, paprika, salt, and pepper.",
      "Spread on a baking sheet and roast for 18-20 minutes until tender and lightly caramelized.",
      "Heat remaining olive oil in a large skillet over medium heat. Add black beans and cook for 5 minutes, mashing slightly.",
      "Season beans with salt, pepper, and a pinch of cumin. Add half the lime juice and cook 2 more minutes.",
      "Mix Greek yogurt with remaining lime juice, cilantro, salt, and pepper to make the sauce.",
      "Warm corn tortillas in a dry skillet or microwave until pliable.",
      "Fill each tortilla with roasted sweet potatoes, seasoned black beans, and shredded cabbage.",
      "Top with avocado slices, pumpkin seeds, and cilantro lime sauce. Serve with hot sauce if desired."
    ],
    youtubeSearch: "black bean sweet potato tacos healthy vegetarian"
  },
  {
    id: 7,
    title: "Roasted Vegetable and White Bean Soup",
    prepTime: "20 minutes",
    cookTime: "40 minutes",
    servings: "6 servings",
    healthNote: "White beans provide soluble fiber and plant protein. Roasted vegetables add antioxidants while olive oil contributes heart-healthy monounsaturated fats.",
    ingredients: [
      "2 cans (15 oz each) cannellini beans, drained and rinsed",
      "2 large carrots, chopped",
      "3 celery stalks, chopped",
      "1 large zucchini, diced",
      "1 red bell pepper, chopped",
      "1 yellow bell pepper, chopped",
      "4 cloves garlic, minced",
      "6 cups low-sodium vegetable broth",
      "1 can (14.5 oz) diced tomatoes",
      "1/4 cup olive oil",
      "2 tsp dried thyme",
      "1 tsp dried rosemary",
      "2 bay leaves",
      "2 cups fresh kale, chopped",
      "2 tbsp fresh lemon juice",
      "Salt and black pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Toss carrots, celery, zucchini, and bell peppers with 3 tbsp olive oil, thyme, rosemary, salt, and pepper.",
      "Spread vegetables on a large baking sheet and roast for 25-30 minutes until tender and lightly browned.",
      "Heat remaining olive oil in a large pot over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Add roasted vegetables, cannellini beans, vegetable broth, diced tomatoes, and bay leaves to the pot.",
      "Bring to a boil, then reduce heat and simmer for 15 minutes to blend flavors.",
      "Stir in chopped kale and cook for 3-4 minutes until wilted. Remove bay leaves.",
      "Season with salt, pepper, and lemon juice. Ladle into bowls and garnish with fresh parsley."
    ],
    youtubeSearch: "roasted vegetable white bean soup healthy"
  },
  {
    id: 8,
    title: "Walnut-Crusted Portobello Mushrooms with Quinoa Pilaf",
    prepTime: "15 minutes",
    cookTime: "25 minutes",
    servings: "4 servings",
    healthNote: "Walnuts are rich in omega-3 fatty acids and help reduce LDL cholesterol. Portobello mushrooms provide umami flavor while quinoa adds complete protein and fiber.",
    ingredients: [
      "4 large portobello mushroom caps, stems removed",
      "1 cup quinoa",
      "2 cups low-sodium vegetable broth",
      "1 cup walnuts, finely chopped",
      "1/2 cup whole wheat breadcrumbs",
      "3 cloves garlic, minced",
      "1/4 cup olive oil",
      "2 tbsp balsamic vinegar",
      "2 tsp dried Italian seasoning",
      "1 tsp dried thyme",
      "2 cups baby spinach",
      "1 cup cherry tomatoes, halved",
      "1/4 cup fresh basil, chopped",
      "2 tbsp pine nuts, toasted",
      "Salt and black pepper to taste",
      "Lemon wedges for serving"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Clean mushroom caps and remove dark gills with a spoon.",
      "Mix chopped walnuts, breadcrumbs, 2 cloves minced garlic, 2 tbsp olive oil, Italian seasoning, thyme, salt, and pepper.",
      "Brush mushroom caps with balsamic vinegar and season with salt and pepper. Press walnut mixture onto gill side of mushrooms.",
      "Place on a baking sheet and bake for 18-20 minutes until mushrooms are tender and crust is golden.",
      "Meanwhile, rinse quinoa and cook in vegetable broth according to package directions (about 15 minutes).",
      "Heat remaining olive oil in a large skillet. Add remaining garlic and cook for 1 minute.",
      "Add cooked quinoa, spinach, and cherry tomatoes. Toss until spinach wilts, about 2-3 minutes.",
      "Season quinoa pilaf with salt, pepper, and fresh basil. Serve mushrooms over quinoa, garnished with pine nuts and lemon wedges."
    ],
    youtubeSearch: "walnut crusted portobello mushrooms quinoa healthy"
  },
  {
    id: 9,
    title: "Mediterranean Stuffed Eggplant with Pine Nuts",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: "4 servings",
    healthNote: "Eggplant contains fiber and antioxidants that support heart health. Pine nuts and olive oil provide beneficial fats that help improve cholesterol ratios.",
    ingredients: [
      "2 large eggplants, halved lengthwise",
      "1 cup cooked brown rice",
      "1/2 cup pine nuts, toasted",
      "1 can (14.5 oz) diced tomatoes, drained",
      "3 cloves garlic, minced",
      "1/4 cup olive oil",
      "2 tsp dried oregano",
      "1 tsp dried basil",
      "1/2 tsp ground cinnamon",
      "1/4 tsp allspice",
      "1/2 cup fresh parsley, chopped",
      "1/4 cup fresh mint, chopped",
      "2 tbsp tomato paste",
      "1/4 cup raisins",
      "2 tbsp lemon juice",
      "Salt and black pepper to taste",
      "Fresh herbs for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Score eggplant flesh in a crosshatch pattern, brush with 2 tbsp olive oil, and season with salt and pepper.",
      "Place cut-side down on a baking sheet and roast for 25 minutes until flesh is tender.",
      "Let cool, then scoop out flesh, leaving 1/2-inch border. Chop scooped flesh and set aside.",
      "Heat remaining olive oil in a large skillet over medium heat. Add minced garlic and cook for 1 minute.",
      "Add chopped eggplant flesh, diced tomatoes, tomato paste, oregano, basil, cinnamon, and allspice.",
      "Cook for 8-10 minutes until mixture thickens. Stir in brown rice, pine nuts, raisins, parsley, and mint.",
      "Season with salt, pepper, and lemon juice. Remove from heat.",
      "Fill eggplant shells with the mixture and bake for 15-20 minutes until heated through. Garnish with fresh herbs before serving."
    ],
    youtubeSearch: "mediterranean stuffed eggplant pine nuts healthy"
  }
];
